app/models.py
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from app import db
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):

    __tablename__ = 'users'
    
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(),index =True)
    email = db.Column(db.String(),unique = True,index = True)
    bio = db.Column(db.String())
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String())
    blogs = db.relationship('Blog',backref = 'user', lazy = 'dynamic')
    comments = db.relationship('Comment',backref = 'user',lazy ='dynamic')
 

    @property
    def password(self):
        raise AttributeError('You cannot access password')

    @password.setter
    def password(self,password):
        self.pass_secure = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

          
    
    def __repr__(self):
        return f'user {self.username}'


class Blog(db.Model):
    __tablename__ = 'blog'
    
    id = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String)
    blog =db.Column(db.String(),index = True)
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))
    comments = db.relationship('Comment',backref = 'blog', lazy ='dynamic')

    
    
class Comment(db.Model):
    __tablename__ = 'comment'

    id = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String)
    comment =db.Column(db.String(),index = True)
    blog_id = db.Column(db.Integer,db.ForeignKey('blog.id'))
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField,SubmitField,StringField,RadioField
from wtforms.validators import  Required

class UpdateProfile(FlaskForm):
    
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

class BlogForm(FlaskForm):

    Title = StringField('Tell us about you.',validators = [Required()])
    blog = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):

    Title = StringField('Tell us about you.',validators = [Required()])
    comment = TextAreaField('Express your thoughts.',validators = [Required()])
    submit = SubmitField('submit')

app/__init__.py
from flask import Flask
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail

login_manager = LoginManager()
'''
The login manager contains the code that lets your application and Flask-Login work together
'''
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()

db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)

mail = Mail()

def create_app(config_name):

    app = Flask(__name__)

    app.config.from_object(config_options[config_name])
    # config_options[config_name].init_app(app)
     
    # configure UploadSet
    configure_uploads(app,photos) 

    #initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix ='/authenticate')
    
    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,forms

app/main/views.py
from flask_login import login_required,current_user
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..models import User,Comment,Blog
from .forms import UpdateProfile,BlogForm,CommentForm
from .. import db,photos


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)
    
    return render_template("profile/profile.html",user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/',methods=['GET','POST'])
def index():
    blogs = Blog.query.all()
    return render_template('index.html',blogs = blogs)

@main.route('/add/blog',methods = ['GET','POST'])
def add_blog():
    form = BlogForm()

    if form.validate_on_submit():
        title = form.Title.data
        blog = form.blog.data
        #category = form.category.data
        
        new_blog = Blog(title = title, blog = blog, user = current_user)
        db.session.add(new_blog)
        db.session.commit()
        return redirect(url_for('main.index'))

    return render_template('add_blog.html', form = form)


@main.route('/add/comment/<blog_id>',methods = ['GET','POST'])
def add_comment(blog_id):
    form = CommentForm()
    blog = Blog.query.filter_by(id = blog_id).first()
    if form.validate_on_submit():
        title = form.Title.data
        comment = form.comment.data
        new_comment = Comment(title = title, comment = comment, user = current_user, blog = blog)
        db.session.add(new_comment)
        db.session.commit()
        return redirect(url_for('main.index'))
        
    return render_template('add_comment.html', form = form)

@main.route('/view/comment<blog_id>',methods = ['GET','POST'])
def view_comment(blog_id):
    blog = Blog.query.filter_by(id = blog_id).first()
    comments = Comment.query.filter_by(blog_id = blog.id)
        
    return render_template('view_comment.html', comments = comments)

app/templates/add_blog.html
{% import 'bootstrap/wtf.html' as wtf%}
{% extends 'base.html' %}

{% block content%}
{{wtf.quick_form(form)}}

{% endblock %}

app/templates/add_comment.html
{% import 'bootstrap/wtf.html' as wtf%}
{% extends 'base.html' %}

{% block content%}
{{wtf.quick_form(form)}}
{% endblock %}

app/templates/base.html
{%extends 'bootstrap/base.html'%}
<!-- Navbar block -->
{% block navbar %}
{% include 'navbar.html'%}
{% endblock %}

app/templates/index.html
{% extends 'base.html' %} {% block styles %} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}" />
{% endblock %} 

{% block content%}
<div class="container">
    <a href="{{url_for('main.add_blog')}}">Add blog</a>
    <h3>How to Immerse Yourself in Spanish When You Don’t Live Abroad</h3>
    <h5>Watch Spanish Videos on FluentU</h5>
    <h6>
        Watching authentic videos—videos made by native Spanish speakers for a native-speaking audience—is an excellent method
        of simulating the immersive experience of being abroad in a Spanish-speaking country.
        
        A great place to access authentic Spanish videos online is right here at FluentU. FluentU has put together a collection
        of the best real-world Spanish video content from the web, and all of the videos can all be watched with Spanish
        subtitles—score!
        
        The videos types range from commercials and music videos to funny homemade mini-movies and speeches—so no matter your
        interests or level, you’ll find something excellent to watch.

    </h6>

    {% for blog in blogs %}
        <p>{{blog.blog}}</p>
        <a href="{{url_for('main.add_comment',blog_id = blog.id)}}">Add comment</a>
        <a style="margin-left:90px;" href="{{url_for('main.view_comment',blog_id = blog.id)}}">View comment</a>
    {% endfor %}
    
{% endblock %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation" style="background-color:black">
    <div class="container-fluid">
        <div class="navbar-header">

            <a class="btn btn-primary" href="/"> Blog </a>
        </div>

        <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li><a class="btn btn-primary" style="margin-right:20px" href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
            <br>
            <li><a class="btn btn-primary" href="{{url_for('auth.logout')}}">Sign out</a></li>
            {% else %}
            <li><a class="btn btn-primary" href="{{url_for('auth.login')}}">Sign in</a></li>
            {%endif%}
        </ul>

    </div>
</div>

app/templates/profile/add_pitch.html
{% import 'bootstrap/wtf.html' as wtf%}
{% extends 'base.html' %}

{% block content%}
{{wtf.quick_form(form)}}

{% endblock %}

app/templates/profile/navbar.html
<div class="navbar navbar-inverse" role="navigation" style="background-color:black">
    <div class="container-fluid">
        <div class="navbar-header">

            <a class="btn btn-primary" href="/"> Pitch </a>
        </div>

        <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li><a class="btn btn-primary" style="margin-right:20px" href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
            <br>
            <li><a class="btn btn-primary" href="{{url_for('auth.logout')}}">Sign out</a></li>
            {% else %}
            <li><a class="btn btn-primary" href="{{url_for('auth.login')}}">Sign in</a></li>
            {%endif%}
        </ul>

    </div>
</div>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>

            <!--Displaying user bio-->
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %}
        </div>

        <!--Display profile photo-->
        <div class="col-md-4">

            {% if user.profile_pic_path %}
            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {%else%}
            <p>No profile picture</p>
            {% endif %}
            {% if user == current_user %}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">

                <input type="file" name="photo" class="form-control" required>
                <input type="submit">
            </form>
            {% endif %}
            {%if user == current_user%}
            <a href="{{url_for('main.update_profile',uname= user.username)}}">Edit Profile</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/view_comment.html
{% extends 'base.html' %}

{% block content%}
{% for comment in comments%}
<h3>{{comment.title}}</h3>
<p>{{comment.comment}}</p>
<p>By{{comment.user.username}}</p>
{% endfor %}
{% endblock %}